### ISSUE TITLE
Migrate models to jozu hub

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/modelkit-factory#4]
Migrate the ModelKits that are hosted on ghcr to Jozu Hub.

**Comment by gorkem** [comment]
gemma models are hitting https://github.com/ggerganov/llama.cpp/issues/7923

**Comment by amisevsk** [comment]
Included in this: we should not forget to update modelkit references where appropriate (e.g. the fine-tuning sample is on jozu.ml but references llama-3 on ghcr.io

**Comment by gorkem** [comment]
fine-tuning sample is from my local and not produced by the the factory.
